unpackaged/main/default/objects/Bundle_Plan__c/Bundle_Plan__c.object-meta.xml
<CustomObject>
    <description>Bundle Plans group products into a single bundle with an associated discount, and related product prices. They can be added to Opportunities to automate/smooth the selling process.</description>
    <label>Bundle Plan</label>
    <nameField>
        <label>Bundle Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundle Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bundle_Plan__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If a bundle isn&#39;t active, it won&#39;t show in search lists.</description>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Plan__c/fields/Plan_Discount__c.field-meta.xml
<CustomField>
    <fullName>Plan_Discount__c</fullName>
    <inlineHelpText>By default, all product will be discounted by this amount. (This can be overridden after they have been added to the Opportunity)</inlineHelpText>
    <label>Plan Discount</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Plan__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Bundle Plans</relationshipLabel>
    <relationshipName>Bundle_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Plan__c/fields/Tier_Plan__c.field-meta.xml
<CustomField>
    <fullName>Tier_Plan__c</fullName>
    <label>Tier Plan</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tier_Plan</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/Bundle_Product__c.object-meta.xml
<CustomObject>
    <description>Links a product to a bundle for fun and profitable times.</description>
    <label>Bundle Product</label>
    <nameField>
        <displayFormat>PLPR-{0000}</displayFormat>
        <label>Bundle Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bundle_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <formula>TEXT( Product__r.Billing_Frequency__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Frequency</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <formula>TEXT(Product__r.Billing_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/fields/Bundle_Plan__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Plan__c</fullName>
    <label>Bundle Plan</label>
    <referenceTo>Bundle_Plan__c</referenceTo>
    <relationshipLabel>Bundle Products</relationshipLabel>
    <relationshipName>Bundle_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/fields/Discount_Override__c.field-meta.xml
<CustomField>
    <fullName>Discount_Override__c</fullName>
    <inlineHelpText>This value will *override* the Bundle&#39;s default discount level if it&#39;s populated. Leave blank to apply the Bundle Discount.</inlineHelpText>
    <label>Percent Discount Override</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/fields/Fixed_Price_Discount_Override__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price_Discount_Override__c</fullName>
    <label>Fixed Price Discount Override</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/fields/Minimum_Price_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Price_Allowed__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The product cannot be discounted to less than this price.</inlineHelpText>
    <label>Minimum Price Allowed</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>LInk to an Active product. The product needs to be in the Bundle Plan&#39;s pricebook.</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Products (Product)</relationshipLabel>
    <relationshipName>Bundle_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PricebookEntry/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <formula>TEXT(Product2.Billing_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Billing_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Recurring (Not Discountable)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Bundle.recordType-meta.xml
<RecordType>
    <fullName>Bundle</fullName>
    <active>true</active>
    <description>Bundles consist of links to other products</description>
    <label>Bundle</label>
</RecordType>

unpackaged/main/default/globalValueSets/Tier_Plan.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Launch</fullName>
    </customValue>
    <customValue>
        <fullName>Brand</fullName>
    </customValue>
    <customValue>
        <fullName>Growth</fullName>
    </customValue>
    <customValue>
        <fullName>Premium</fullName>
    </customValue>
    <customValue>
        <fullName>Elite</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Base</fullName>
    </customValue>
    <customValue>
        <fullName>Launch+</fullName>
    </customValue>
    <customValue>
        <fullName>Brand+</fullName>
    </customValue>
    <customValue>
        <fullName>Growth+</fullName>
    </customValue>
    <customValue>
        <fullName>Premium+</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Leads Pro</fullName>
    </customValue>
    <customValue>
        <fullName>SEO Pro</fullName>
    </customValue>
    <customValue>
        <fullName>Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Presence Premier</fullName>
    </customValue>
    <customValue>
        <fullName>Leads Premier</fullName>
    </customValue>
    <customValue>
        <fullName>SEO Premier</fullName>
    </customValue>
    <customValue>
        <fullName>All In Premier</fullName>
    </customValue>
    <masterLabel>Tier Plan</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Test_BundleProduct.cls
@istest
public class Test_BundleProduct {

    @testsetup
    public static void createProducts(){
        // I need at least three products, or I need more than one test
        // - Add a product with no discount override
        // - Add a product with a percentage discount override
        // - Add a product with no perentage discount override
        List<Product2> allProducts = new List<Product2>();
        
        Product2 theProduct = new Product2();
        	theProduct.RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('One-Time Fees').getRecordTypeId();
        	theProduct.Name = 'Setup for Tests';
        	theProduct.isActive = true;
        	theProduct.Billing_Type__c = 'One-Time';
        allProducts.add(theProduct);
        
        Product2 theOtherProduct = new Product2();
        	theOtherProduct.RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Recurring Revenue').getRecordTypeId();
        	theOtherProduct.Name = 'Not Setup for Tests';
        	theOtherProduct.isActive = true;
        	theOtherProduct.Billing_Type__c = 'Recurring';
        	theOtherProduct.Billing_Frequency__c = 'Monthly';
        allProducts.add(theOtherProduct);
        
        Product2 theOtherOtherProduct = new Product2();
        	theOtherOtherProduct.RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Recurring Revenue').getRecordTypeId();
        	theOtherOtherProduct.Name = 'Also Not Setup for Tests';
        	theOtherOtherProduct.isActive = true;
        	theOtherOtherProduct.Billing_Type__c = 'Recurring';
        	theOtherOtherProduct.Billing_Frequency__c = 'Monthly';
        allProducts.add(theOtherOtherProduct);

        insert allProducts;

        
        // Now we need pricebook entries for all these
        List<PricebookEntry> allPricebookEntries = new List<PricebookEntry>();
        for(Product2 thisProduct : allProducts){
            PricebookEntry theEntry = new PricebookEntry();
            	theEntry.Pricebook2Id = Test.getStandardPricebookId();
            	theEntry.Product2Id = thisProduct.Id;
            	theEntry.isActive = true;
            	theEntry.UnitPrice = 500;
            allPricebookEntries.add(theEntry);
        }
        
        insert allPricebookEntries;
    }
    
    @istest
    public static void createABundle(){

		List<Product2> allProducts = [SELECT Id FROM Product2];
        System.Debug(allProducts);


        List<PricebookEntry> allPricebookEntries = new List<PricebookEntry>();
        Map<String, PricebookEntry> allPricebookEntriesByProductName = new Map<String, PricebookEntry>();
        allPricebookEntries = [SELECT Id,
                               PricebookEntry.Name,
                               Pricebook2Id,
                               Pricebook2.isStandard,
                               Product2Id,
                               Product2.Name,
                               UnitPrice,
                               UseStandardPrice
                               FROM PricebookEntry
                               WHERE Pricebook2Id = :Test.getStandardPricebookId()];
        System.Debug(allPricebookEntries);
        for(PricebookEntry thePricebookEntry : allPricebookEntries){
            allPricebookEntriesByProductName.put(thePricebookEntry.Product2.Name, thePricebookEntry);
        }

        String thePricebookId = Test.getStandardPricebookId();
        // String thePricebookId = allPricebookEntries[0].Pricebook2Id;
        System.Debug('Pricebook ID: ' + thePricebookId);
        
        // Create the Bundle
        Bundle_Plan__c dasPlan = new Bundle_Plan__c();
            dasPlan.Name = 'Test Bundle';
            dasPlan.Price_Book__c = thePricebookId;
        	dasPlan.Plan_Discount__c = 5;
        	dasPlan.Tier_Plan__c = 'Launch';
        insert dasPlan;
        
        decimal defaultDiscount = 1 - (dasPlan.Plan_Discount__c/100);
        
        // Now we start inserting products into the bundle so we create a list
 		List<Bundle_Product__c> allBundleProducts = new List<Bundle_Product__c>();  
 		// First we insert a product with the standard price

        Bundle_Product__c theProduct = new Bundle_Product__c();
	        theProduct.Bundle_Plan__c = dasPlan.Id;
        	theProduct.Product__c = allPricebookEntries[0].Product2Id;
        	System.Debug('Product Pricebook: ' + allPricebookEntries[0].Pricebook2Id);
        	// theProduct.Minimum_Price_Allowed__c = (allPricebookEntries[0].UnitPrice * defaultDiscount) - 0.01;
        	theProduct.Fixed_Price_Discount_Override__c = null;
        	theProduct.Discount_Override__c = null;
		allBundleProducts.add(theProduct);
        
 		Bundle_Product__c theProduct1 = new Bundle_Product__c();
	        theProduct1.Bundle_Plan__c = dasPlan.Id;
        	theProduct1.Product__c = allPricebookEntries[1].Product2Id;
        	// theProduct1.Minimum_Price_Allowed__c = allPricebookEntries[1].UnitPrice * defaultDiscount;
        	theProduct1.Fixed_Price_Discount_Override__c = 0;
        	theProduct1.Discount_Override__c = null;
		allBundleProducts.add(theProduct1);        	

 		Bundle_Product__c theProduct2 = new Bundle_Product__c();
	        theProduct2.Bundle_Plan__c = dasPlan.Id;
        	theProduct2.Product__c = allPricebookEntries[2].Product2Id;
        	// theProduct2.Minimum_Price_Allowed__c = allPricebookEntries[2].UnitPrice * (defaultDiscount - 0.05);
        	theProduct2.Fixed_Price_Discount_Override__c = null;
        	theProduct2.Discount_Override__c = dasPlan.Plan_Discount__c + 1;
		allBundleProducts.add(theProduct2);        	

        insert allBundleProducts;
        
        dasPlan.isActive__c = true;
        update dasPlan;

    }
}