unpackaged/main/default/objects/Bundle_Plan__c/Bundle_Plan__c.object-meta.xml
<CustomObject>
    <description>Bundle Plans group products into a single bundle with an associated discount, and related product prices. They can be added to Opportunities to automate/smooth the selling process.</description>
    <label>Bundle Plan</label>
    <nameField>
        <label>Bundle Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundle Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bundle_Plan__c/fields/Number_of_Other_Products__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Other_Products__c</fullName>
    <label>Number of Other Products</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Plan__c/fields/Number_of_Setup_Fee_Products__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Setup_Fee_Products__c</fullName>
    <inlineHelpText>Calculated by trigger.</inlineHelpText>
    <label>Number of Setup Fee Products</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Plan__c/fields/Total_Discount_Price_of_Other_Products__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount_Price_of_Other_Products__c</fullName>
    <description>Set in the Bundle Product Trigger Handler.</description>
    <inlineHelpText>Total of the Bundle Price of all associated products that do NOT hav Product Family of Setup Fee.</inlineHelpText>
    <label>Total Discount Price of Other Products</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Plan__c/fields/Total_Discount_Price_of_Setup_Fees__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount_Price_of_Setup_Fees__c</fullName>
    <description>Set in the Bundle Product Trigger Handler.</description>
    <inlineHelpText>Total of the default bundle price of all Bundle Products that have a Product Family of Setup Fee.</inlineHelpText>
    <label>Total Discount Price of Setup Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Plan__c/fields/Total_List_Price_of_Other_Products__c.field-meta.xml
<CustomField>
    <fullName>Total_List_Price_of_Other_Products__c</fullName>
    <description>Set in the Bundle Product Trigger Handler.</description>
    <inlineHelpText>Total of the List Price of all associated products that do NOT hav Product Family of Setup Fee.</inlineHelpText>
    <label>Total List Price of Other Products</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Plan__c/fields/Total_List_Price_of_Setup_Fee_Products__c.field-meta.xml
<CustomField>
    <fullName>Total_List_Price_of_Setup_Fee_Products__c</fullName>
    <inlineHelpText>Total of the list price of all Bundle Products that have a Product Family of Setup Fee.</inlineHelpText>
    <label>Total List Price of Setup Fee Products</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Plan__c/fields/Total_Minimum_Price_of_Other_Products__c.field-meta.xml
<CustomField>
    <fullName>Total_Minimum_Price_of_Other_Products__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Set in the Bundle Product Trigger Handler.</description>
    <inlineHelpText>Total of the Minimum Allows Price on the Bundle Product of all associated products that do NOT hav Product Family of Setup Fee.</inlineHelpText>
    <label>Total Minimum Price of Other Products</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Plan__c/fields/Total_Minimum_Price_of_Setup_Fees__c.field-meta.xml
<CustomField>
    <fullName>Total_Minimum_Price_of_Setup_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Set in the Bundle Product Trigger Handler</description>
    <inlineHelpText>Total of the minimum price of all Bundle Products that have a Product Family of Setup Fee.</inlineHelpText>
    <label>Total Minimum Price of Setup Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/Bundle_Product__c.object-meta.xml
<CustomObject>
    <description>Links a product to a bundle for fun and profitable times.</description>
    <label>Bundle Product</label>
    <nameField>
        <displayFormat>PLPR-{0000}</displayFormat>
        <label>Bundle Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bundle_Product__c/fields/Bundle_Plan__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Plan__c</fullName>
    <label>Bundle Plan</label>
    <referenceTo>Bundle_Plan__c</referenceTo>
    <relationshipLabel>Bundle Products</relationshipLabel>
    <relationshipName>Bundle_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/fields/Bundle_Price__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Price__c</fullName>
    <label>Bundle Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/fields/Minimum_Price_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Price_Allowed__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The product cannot be discounted to less than this price.</inlineHelpText>
    <label>Minimum Price Allowed</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>Copied from the Product whenever the Bundle Product is edited.</description>
    <label>Product Family</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bundle_Product__c/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <description>The price this product is listed in the *standard* price book for.</description>
    <label>Standard Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/BundleProductTriggerHandler.cls
public class BundleProductTriggerHandler {

    public class productPrices {
        Decimal setupFeeListPrice = 0;
        Decimal setupFeeDiscountPrice = 0;
        Decimal setupFeeMinimumPrice = 0;
        Decimal numberOfSetupFeeProducts = 0;
        Decimal otherFeeListPrice = 0;
        Decimal otherFeeDiscountPrice = 0;
        Decimal otherFeeMinimumPrice = 0;
        Decimal numberOfOtherProducts = 0;
    }
    
    public static void updateBundlePlanTotals(Set<Id> allBundlePlanIds){
	    System.Debug('Updating Bundle Plan Totals');
        System.Debug(allBundlePlanIds);

        // We want to calculate a bunch of values here, including totals and discounts
        // there are too many to use Roll Up fields, so we do the Trigger
//		Set<Id> allBundlePlanIds = new Set<Id>();
//        for(Bundle_Product__c theProduct : updatedBundleProducts){
//            allBundlePlanIds.add(theProduct.Bundle_Plan__c);
//        }
        List<Bundle_Product__c> allBundleProducts = new List<Bundle_Product__c>();
        Map<String, productPrices> totalPricesByBundleProductId = new Map<String, productPrices>();
        
        // We need to get *all* the products related to the Plan, not just the one in the Trigger
		allBundleProducts = [SELECT Id,
                             Bundle_Plan__c,
                             Product_Family__c,
                             Standard_Price__c,
                             Bundle_Price__c,
                             Minimum_Price_Allowed__c 
                             FROM Bundle_Product__c
                             WHERE Bundle_Plan__c IN :allBundlePlanIds];
        
        Map<String, Bundle_Plan__c> bundlePlansById = new Map<String, Bundle_Plan__c>();

        for(Bundle_Product__c theProduct : allBundleProducts){
                // check to see if our map already has a value for this bundle plan
                // if it does, we add to it. If it doesn't we set a new value
                productPrices thePrices = new productPrices();
            if(theProduct.Minimum_Price_Allowed__c == null){ theProduct.Minimum_Price_Allowed__c = 0; }

            	// Check to see if we've seen this before and get the values
            	if(totalPricesByBundleProductId.containsKey(theProduct.Bundle_Plan__c) == true) {
                    thePrices = totalPricesByBundleProductId.get(theProduct.Bundle_Plan__c);
                }

                    if(theProduct.Product_Family__c == 'Setup Fee'){
                        thePrices.setupFeeListPrice = thePrices.setupFeeListPrice + theProduct.Standard_Price__c;
                        thePrices.setupFeeDiscountPrice = thePrices.setupFeeDiscountPrice + theProduct.Bundle_Price__c;
                        thePrices.setupFeeMinimumPrice = thePrices.setupFeeMinimumPrice + theProduct.Minimum_Price_Allowed__c;
                        thePrices.numberOfSetupFeeProducts = thePrices.numberOfSetupFeeProducts + 1;
                    } else {
                        thePrices.otherFeeListPrice = thePrices.otherFeeListPrice + theProduct.Standard_Price__c;
                        thePrices.otherFeeDiscountPrice = thePrices.otherFeeDiscountPrice + theProduct.Bundle_Price__c;
                        thePrices.otherFeeMinimumPrice = thePrices.otherFeeMinimumPrice + theProduct.Minimum_Price_Allowed__c;
                        thePrices.numberOfOtherProducts = thePrices.numberOfOtherProducts + 1;
                    }
                    totalPricesByBundleProductId.put(theProduct.Bundle_Plan__c, thePrices);

        		Bundle_Plan__c theUpdatedPlan = new Bundle_Plan__c();
        		  	theUpdatedPlan.Id = theProduct.Bundle_Plan__c;
        		  	theUpdatedPlan.Total_List_Price_of_Other_Products__c   = totalPricesByBundleProductId.get(theProduct.Bundle_Plan__c).otherFeeListPrice;
        		  	theUpdatedPlan.Total_Discount_Price_of_Other_Products__c  = totalPricesByBundleProductId.get(theProduct.Bundle_Plan__c).otherFeeDiscountPrice;
        		  	theUpdatedPlan.Total_Minimum_Price_of_Other_Products__c  = totalPricesByBundleProductId.get(theProduct.Bundle_Plan__c).otherFeeMinimumPrice;
        		  	theUpdatedPlan.Number_of_Other_Products__c  = totalPricesByBundleProductId.get(theProduct.Bundle_Plan__c).numberOfOtherProducts;
        		  	theUpdatedPlan.Total_List_Price_of_Setup_Fee_Products__c  = totalPricesByBundleProductId.get(theProduct.Bundle_Plan__c).setupFeeListPrice;
        		  	theUpdatedPlan.Total_Discount_Price_of_Setup_Fees__c  = totalPricesByBundleProductId.get(theProduct.Bundle_Plan__c).setupFeeDiscountPrice;
        		  	theUpdatedPlan.Total_Minimum_Price_of_Setup_Fees__c  = totalPricesByBundleProductId.get(theProduct.Bundle_Plan__c).setupFeeMinimumPrice;
        		  	theUpdatedPlan.Number_of_Setup_Fee_Products__c  = totalPricesByBundleProductId.get(theProduct.Bundle_Plan__c).numberOfSetupFeeProducts;
            	System.Debug(theUpdatedPlan);
            
            	bundlePlansById.put(theProduct.Bundle_Plan__c, theUpdatedPlan);
            	System.Debug(bundlePlansById);

        }
        
        // Now we have our list, let's update!
        update bundlePlansById.values();
        
                
            }
    
    
        }